POST http://localhost:24280/Ticket HTTP/1.1
content-type: application/json

{
    "CustomerName": "Anton Kalcik",
    "Movie": "Mr.Robot",
    "MovieTheater": "Apollo Wien",
    "ReservationDateTime": "2017-04-30T18:30:00.0000000-00:00",
    "SeatNumber": "1"
}